#!/usr/bin/env bash

sudo apt install zsh
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone --depth=1 https://gitee.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/themes/powerlevel10k
sed -i 's/ZSH_THEME=".*"/ZSH_THEME="powerlevel10k\/powerlevel10k"/' ~/.zshrc
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
git clone https://github.com/agkozak/zsh-z "$ZSH_CUSTOM"/plugins/zsh-z
sudo apt install cargo
cargo install eza
mv ~/.cargo/bin/eza ~/bin
sudo apt-get install fzf
sed -i 's/plugins=(git)/plugins=\( git pip python node npm github zsh-syntax-highlighting zsh-autosuggestions zsh-z fzf \)/' ~/.zshrc

# vim: set filetype=zsh :
